name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for SonarCloud

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install radon
          pip install bandit

      - name: Install HDL tools
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog yosys graphviz

      - name: Run complexity checks
        run: |
          radon cc . -a -s -n B
          radon mi . -s

      - name: Run security checks
        continue-on-error: true
        run: |
          bandit -r . -f json -o bandit-report.json

      - name: Run tests with coverage
        run: |
          pytest hdlopt/tests -v --cov=hdlopt --cov-report=xml

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # Eclipse Temurin distribution
          java-version: "17" # Use Java 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Setup SonarCloud Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: Run SonarCloud Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=uzairgheewala_HDLOpt \
            -Dsonar.organization=uzairgheewala \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=. \
            -Dsonar.tests=hdlopt/tests \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.verbose=true \
            -Dsonar.qualitygate.wait=true
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_ACCESS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-reports
          path: |
            bandit-report.json
            coverage.xml
