name: Update Module Status

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

jobs:
  update-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WIKI_ACCESS_TOKEN }} # Add this line
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas matplotlib PyGithub
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update module status
        run: python .github/scripts/update_status.py
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_ACCESS_TOKEN }}

      - name: Update status badge
        run: |
          STATUS=$(cat status.json | jq -r '.percent_implemented')
          COLOR=$([ $STATUS -lt 30 ] && echo "red" || ([ $STATUS -lt 70 ] && echo "yellow" || echo "green"))
          curl -X POST https://img.shields.io/badge/Modules%20Implemented-${STATUS}%25-${COLOR} \
            -d "link=https://github.com/${{ github.repository }}/blob/main/status.json" \
            -d "logo=github"
