name: Verify New Modules

on:
  push:
    paths:
      - "src/**/*.v" # Trigger when Verilog files are added/modified in src/

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run HDLOpt Analysis
        run: |
          for file in src/*.v; do
            if [ -f "$file" ]; then
              module_name=$(basename "$file" .v)
              echo "Analyzing module: $module_name"
              python -m hdlopt.runner analyze "$module_name"
            fi
          done

      - name: Move Verified Modules
        run: python .github/scripts/verify_module.py

      - name: Commit Changes
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add modules/
          git commit -m "Auto-verify and move modules" || echo "No changes to commit"
          git push
